name: tyssue
channels:
  - conda-forge
dependencies:
- cmake
- pybind11
- pip
- boost-cpp
- mpfr
- gmp
- cgal
- python>=3.8
- numpy
- scipy
- matplotlib
- pandas
- pytables
- jupyter
- notebook
- quantities
- ipywidgets
- pythreejs
- ipyvolume
- vispy
- meshio
- zarr
- xarray
- nbsphinx
- jupyter-book
